MCKIN-12757 fix courses count by excluding company admins
edx-solutions/organizations-edx-platform-extensions pull request #45
Opened 2020-03-18 12:50 UTC by mudassir-hafeez

Fixed organization courses count

2020-03-18 12:50 UTC, edx-webhook commented
Thanks for the pull request, @mudassir-hafeez! I've created [OSPR-4277](https://openedx.atlassian.net/browse/OSPR-4277) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2020-03-18 13:01 UTC, nasirhjafri requested changes
Please add comments on the code. Thanks @mudassir-hafeez

2020-03-18 13:01 UTC, nasirhjafri commented on edx_solutions_organizations/views.py
> +                main_company = user.organizations.all()[0].id
Get all users in a single query and use prefetch for organizations

2020-03-18 13:01 UTC, nasirhjafri commented on edx_solutions_organizations/views.py
> +            for id, user_id in admin_users:
id is a builtin.

2020-03-19 12:44 UTC, mudassir-hafeez commented on edx_solutions_organizations/views.py
> +                main_company = user.organizations.all()[0].id
@nasirhjafri thanks for reviewing. Actually, prefetch changes the order of the organizations so I refactored the code a bit and added few comments.

2020-03-24 13:53 UTC, musmanmalik commented on edx_solutions_organizations/views.py
> +                k, v in admin_users_dict.items()]
Please use meaningful variables.

2020-03-24 16:28 UTC, mudassir-hafeez commented on edx_solutions_organizations/views.py
> +                k, v in admin_users_dict.items()]
Addressed

2020-03-25 08:46 UTC, nasirhjafri approved these changes

2020-03-25 09:04 UTC, merged