[MCKIN-18911] Review fix for participants count on company detail page
edx-solutions/organizations-edx-platform-extensions pull request #50
Opened 2020-06-22 11:13 UTC by sohaibaslam

Added filter for excluding relevant admin users for a course.

2020-06-22 11:45 UTC, nasirhjafri requested changes
If this fix is intended for Ironwood, please check which version of Django we are using in Ironwood.

2020-06-22 11:45 UTC, nasirhjafri commented on edx_solutions_organizations/views.py
> +                    course_id=OuterRef('course_id'), role__in=roles_to_exclude, user_id=OuterRef('user_id'))
We considered using `OuterRef ` in past. But we are on `Django==1.8.19` and it doesn't have `OuterRef`.

2020-06-22 12:01 UTC, sohaibaslam commented
> If this fix is intended for Ironwood, please check which version of Django we are using in Ironwood.

We are using django==1.11.29 in Ironwood.

2020-06-22 12:57 UTC, moeez96 commented
@sohaibaslam Please rebase your branch to `master-ginko`

2020-06-25 10:23 UTC, nasirhjafri approved these changes

2020-06-25 12:48 UTC, mudassir-hafeez reviewed
please update version in setup.py

2020-06-25 12:59 UTC, merged